analyzer:
  errors:
    todo: ignore
  exclude:
    - "build/**"
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
